some fixes and add mute
KozalakliKozalak/KozalakBot pull request #1
Opened 2017-11-22 21:19 UTC by Serhann

2017-11-22 21:20 UTC, KozalakliKozalak commented
Will review in morning .

2017-11-22 21:23 UTC, Serhann commented
k fixed now 👍

2017-11-22 21:24 UTC, coneforapine requested changes
D.js'te single user için mute ekleme olayı yok diye biliyorum? Mute için rol oluşturmak gerek. Fixler için sağol. Gözümden kaçmış.

2017-11-23 14:08 UTC, Serhann commented
https://discord.js.org/#/docs/main/stable/class/GuildMember?scrollTo=setMute

2017-11-23 14:10 UTC, KozalakliKozalak commented
Voicechannel için bu durum. Text channel için değil.

2017-11-23 15:39 UTC, Serhann commented
o zaman sen yaparsın 👍

2017-11-23 15:46 UTC, KozalakliKozalak commented
Then I'll made my own, pr closed.

2017-11-23 15:46 UTC, closed without merging